P8130 HW3
================
10/16/2020

### Problem 1

*(a) We will employ ‘Two-Sided Paired t-test’ to assess whether the
Systolic BP at 6 months is significantly from the baseline values for
each of the groups: intervention, control.*

*intervention group*

\(H_{0}: \mu_{post}-\mu_{pre}=0\)

\(H_{1}: \mu_{post}-\mu_{pre}\neq 0\)

  - With a pre-specified significance level \(\alpha=0.05\), the test
    statistics

\(t_{stat} = \frac{\overline{d}-0}{s_d/\sqrt{n}}\)

Reject \(H_0\): if \(|t_{stat}|>t_{n-1, 1-\alpha/2}\)

Fail to reject \(H_0\): if \(|t_{stat}|\leq t_{n-1,1-\alpha/2}\)

  - We find the following:

\(\overline{d}=-8.583333\)

\(s_d = 17.1687\)

\(n=36\)

\(t_{stat} = \frac{\overline{d}-0}{s_d/\sqrt{n}}=\frac{-8.583333-0}{17.1687/\sqrt{36}} \cong -2.999645\)

\(t=2.030108\)

\(|t| > t_{35,\ \ 0.975}\)

  - Fail to reject \(H_0\), and conclude that the Systolic BP at 6 month
    is not significant different from the baseline values for the
    intervention group

*control group*

\(H_{0}: \mu_{post}-\mu_{pre}=0\)

\(H_{1}: \mu_{post}-\mu_{pre}\neq 0\)

  - With a pre-specified significance level \(\alpha=0.05\), the test
    statistics

\(t_{stat} = \frac{\overline{d}-0}{s_{d}/\sqrt{n}}\)

Reject \(H_0\): if \(|t_{stat}|>t_{n-1, 1-\alpha/2}\)

Fail to reject \(H_0\): if \(|t_{stat}|\leq t_{n-1,1-\alpha/2}\)

  - We find the following:

\(\overline{d}=-3.333333\)

\(s_d = 14.81312\)

\(n=36\)

\(t_{stat} = \frac{\overline{d}-0}{s_d/\sqrt{n}}=\frac{-3.333333-0}{14.81312/\sqrt{36}} \cong -1.350154\)

\(t=2.030108\)

\(|t_{stat}| < t_{35,\ \ 0.975}\)

  - Fail to reject \(H_0\), and conclude that the Systolic BP at 6 month
    is not significant different from the baseline values for the
    intervention group.

<!-- end list -->

    ## 
    ##  Paired t-test
    ## 
    ## data:  intervention$systolic_post and intervention$systolic_pre
    ## t = -2.9996, df = 35, p-value = 0.004953
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -14.392386  -2.774281
    ## sample estimates:
    ## mean of the differences 
    ##               -8.583333

    ## 
    ##  Paired t-test
    ## 
    ## data:  control$systolic_post and control$systolic_pre
    ## t = -1.3502, df = 35, p-value = 0.1856
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -8.345373  1.678706
    ## sample estimates:
    ## mean of the differences 
    ##               -3.333333

*b) Now perform a test and provide the 95% confidence interval to assess
the Systolic BP absolute changes between the two groups.*

  - Test for Equality of Variance

\(H_{0}: \sigma_{intervention}^{2} = \sigma_{control}^{2}\)

\(H_{1}: \sigma_{intervention}^{2} \neq \sigma_{control}^{2}\)

Compute the F test statistics and critical value:
\(F_{stat} = \frac{s_{intervention}^{2}}{s_{control}^{2}} = \frac{17.1687}{14.81312} \cong 1.3433268\)

\(F_{crit} = F_{35,35,0.975} = 1.9610894\)

  - Decision: At 0.05 significance level, because
    \(F_{stat} < F_{crit}\), we fail to reject \(H_0\) and conclude that
    it is safe to assume variances are equal.

  - Therefore, we have the following C.I:

\(s^2 = \frac{(n_{int}-1)s_{int}^2-(n_{con}-1)s_{con}^2}{n_{int}+n_{con}-2} = \frac{(36-1)17.1687+(36-1)14.81312}{36+36-2} \cong 257.0964\)

\(\overline{X_{int}}-\overline{X_{con}}\ \ \pm t_{n_{int}+n_{con}-2,\ 1-\alpha/2}\times \frac{s}{\sqrt{1/n_1+1/n_2}}\)

\((-8.583333-(-3.333333))\ \ \pm\ 1.995469\times \sqrt{\frac{257.0964}{2/72}}\)

\((-197.1255, 186.6255)\)

  - Conclusion: we are 95% confident that the true Systolic BP absolute
    changes for the two groups is between -197.1255 and 186.6255.
